### ISSUE TITLE
Documentation code is deprecated

### ISSUE THREAD

**Issue by macxtor** [googleapis/java-resourcemanager#738]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-resourcemanager/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Steps to reproduce

The documentation in the readme file is old and shows code that has been deprecated a long time ago. Personally took me a few hours to figure it out to
   -  get specific projects
   - update the project
   - create a new project
   - fetch a list of project
 
The current documentation focus on `v1` of `resourceManager` which is deprecated and the latest version `1.2.5` version of the library resourceManager is on `v3`. The documentation and code samples need to be updated to show the latest code.
 

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by eaball35** [comment]
Any particular docs you are referencing?  I can see both v1 and v3 on [cloud.google.com](https://cloud.google.com/java/docs/reference/google-cloud-resourcemanager/latest/com.google.cloud.resourcemanager.v3)

**Comment by macxtor** [comment]
Hello @eaball35, I'm referring to the readme file on this library.

**Comment by suztomo** [comment]
The readme has moved to https://github.com/googleapis/google-cloud-java/tree/main/java-resourcemanager/ It has updated library version.
