### ISSUE TITLE
JAR for java-resourcemanager

### ISSUE THREAD

**Issue by deliveryhostbuddy** [googleapis/java-resourcemanager#808]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
Hello,

Do we have a JAR for this library? We need to use JAR for development purposes.

**Comment by lqiu96** [comment]
Should be at https://mvnrepository.com/artifact/com.google.cloud/google-cloud-resourcemanager/1.5.0
